---
tasks:
  - name: Git install
    become: true
    yum:
      name: git
  - name: Get lighthouse
    git:
      repo: https://github.com/VKCOM/lighthouse.git
      version: master
      dest: ./lighthouse
    register: copy_remote
  - name: Copy config
    template: 'src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=0664'
    become: true
